### ISSUE TITLE
broken examples

### ISSUE THREAD

**Issue by faif** [tdd/pragmatic-javascript#2]
Hi,

You are probably aware of it, but all examples that point to pocketjavascript.com are broken. Does the URL still belong to you?

Also, the twitter API has been updated and tokens are at minimum necessary so the mashup is also broken. Not your fault, but just FYI :)

Great book BTW :+1:

**Comment by tdd** [comment]
Hey there,

Thank you so much for the nice feedback!

The domain was retired a couple years after the book went out of print. The source code archive can still be downloaded [on the book's page](https://pragprog.com/titles/pg_js/source_code), but the domain itself is done now.

There's basically no maintenance going in at this point. Sorry!

Best,
